stages:
  - docker-build
  
services:
  - name: docker:20.10-dind
    command: ["--insecure-registry=repository.hal.davecutting.uk:5005"]


# Using the prefix PIPE_VAR to denote the variable is made in the pipeline 
variables:
  DOCKER_HOST: "tcp://docker:2375"  # Use non-TLS endpoint
  DOCKER_TLS_CERTDIR: ""           # Disable TLS

  PIPE_VAR_DOCKER_IMAGE: "$CI_REGISTRY/$CI_PROJECT_NAMESPACE"
  PIPE_VAR_PIPELINE_TAG: "$CI_COMMIT_REF_SLUG"
  PIPE_VAR_DEPLOYMENT_TAG: "latest"


docker-build:
  stage: docker-build
  image: docker:20.10-dind
  variables:
    JOB_VAR_DOCKER_IMAGE: $PIPE_VAR_DOCKER_IMAGE:$PIPE_VAR_PIPELINE_TAG
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - echo "Building image $JOB_VAR_DOCKER_IMAGE"
    - docker info
    - docker build -t $JOB_VAR_DOCKER_IMAGE .
    - docker push  $JOB_VAR_DOCKER_IMAGE
  tags: 
    - dockerindocker

